// src/lib/components/shipments/ShipmentFilters.svelte
<script lang="ts">
  let {
    statusFilter,
    typeFilter,
    onStatusChange,
    onTypeChange,
  }: {
    statusFilter: string
    typeFilter: string
    onStatusChange: (value: string) => void
    onTypeChange: (value: string) => void
  } = $props()
</script>

<div class="bg-muted p-4 rounded-lg shadow border border-border mb-6">
  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div>
      <label for="status-filter" class="block text-sm font-medium text-muted-foreground mb-1">
        Status
      </label>
      <select
        id="status-filter"
        value={statusFilter}
        onchange={(e) => onStatusChange(e.currentTarget.value)}
        class="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
      >
        <option value="all">All Statuses</option>
        <option value="draft">Draft</option>
        <option value="finalized">Finalized</option>
      </select>
    </div>

    <div>
      <label for="type-filter" class="block text-sm font-medium text-muted-foreground mb-1">
        Type
      </label>
      <select
        id="type-filter"
        value={typeFilter}
        onchange={(e) => onTypeChange(e.currentTarget.value)}
        class="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
      >
        <option value="all">All Types</option>
        <option value="Domestic">Domestic</option>
        <option value="IntraGulf">Intra-Gulf</option>
        <option value="International">International</option>
      </select>
    </div>
  </div>
</div>

// components/shipments/ShipmentFilters.tsx
interface ShipmentFiltersProps {
  statusFilter: string
  typeFilter: string
  onStatusChange: (value: string) => void
  onTypeChange: (value: string) => void
}

export default function ShipmentFilters({
  statusFilter,
  typeFilter,
  onStatusChange,
  onTypeChange,
}: ShipmentFiltersProps) {
  return (
    <div className="bg-muted p-4 rounded-lg shadow border border-border mb-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-muted-foreground mb-1">
            Status
          </label>
          <select
            value={statusFilter}
            onChange={(e) => onStatusChange(e.target.value)}
            className="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
          >
            <option value="all">All Statuses</option>
            <option value="draft">Draft</option>
            <option value="finalized">Finalized</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-muted-foreground mb-1">
            Type
          </label>
          <select
            value={typeFilter}
            onChange={(e) => onTypeChange(e.target.value)}
            className="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
          >
            <option value="all">All Types</option>
            <option value="Domestic">Domestic</option>
            <option value="IntraGulf">Intra-Gulf</option>
            <option value="International">International</option>
          </select>
        </div>
      </div>
    </div>
  )
}
