// components/shipments/StatsCards.tsx
interface StatsCardsProps {
  total: number
  draft: number
  finalized: number
}

export default function StatsCards({ total, draft, finalized }: StatsCardsProps) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
      <div className="bg-muted p-4 rounded-lg shadow border border-border">
        <div className="text-sm text-muted-foreground">Total Shipments</div>
        <div className="text-2xl font-bold text-foreground">{total}</div>
      </div>
      <div className="bg-muted p-4 rounded-lg shadow border border-border">
        <div className="text-sm text-muted-foreground">Draft</div>
        <div className="text-2xl font-bold text-muted-foreground">{draft}</div>
      </div>
      <div className="bg-muted p-4 rounded-lg shadow border border-border">
        <div className="text-sm text-muted-foreground">Finalized</div>
        <div className="text-2xl font-bold text-premium">{finalized}</div>
      </div>
    </div>
  )
}

// src/lib/components/shipments/StatsCards.svelte
<script lang="ts">
  let { total, draft, finalized }: { total: number; draft: number; finalized: number } = $props()

  const stats = $derived([
    { label: 'Total Shipments', value: total, tone: 'text-foreground' },
    { label: 'Draft', value: draft, tone: 'text-muted-foreground' },
    { label: 'Finalized', value: finalized, tone: 'text-premium' },
  ])
</script>

<!-- A definition list so each number is programmatically tied to its label. -->
<dl class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
  {#each stats as stat (stat.label)}
    <div class="bg-muted p-4 rounded-lg shadow border border-border">
      <dt class="text-sm text-muted-foreground">{stat.label}</dt>
      <dd class="text-2xl font-bold {stat.tone}">{stat.value}</dd>
    </div>
  {/each}
</dl>
