// components/cards/SenderCard.tsx
'use client'

import { User } from 'lucide-react'
import type { CardRules } from '@/lib/types'
import { t } from '@/lib/translations'

interface SenderCardProps {
  rules: CardRules | null
  formData: Record<string, any>
  errors: Record<string, string>
  onChange: (name: string, value: any) => void
  onBlur?: (name: string) => void
  disabled?: boolean
}

export default function SenderCard({
  rules,
  formData,
}: SenderCardProps) {
  const senderName = formData.senderName || ''
  const senderCountry = formData.senderCountry || ''

  return (
    <div className="bg-muted p-4 rounded-lg shadow border border-border">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 bg-nord-frost-1/20 rounded-full flex items-center justify-center">
          <User className="w-5 h-5 text-primary" />
        </div>
        <div className="flex-1">
          <h2 className="text-sm font-medium text-muted-foreground">{t('form.senderInformation')}</h2>
          <p className="text-foreground font-semibold">
            {senderName} - {senderCountry}
          </p>
        </div>
      </div>
      <p className="text-xs text-muted-foreground/70 mt-3">
        Sender details are filled from your account automatically and cannot be edited
      </p>
    </div>
  )
}

// src/lib/components/cards/SenderCard.svelte
<script lang="ts">
  import { User } from 'lucide-svelte'
  import { t } from '$lib/translations'

  let { formData }: { formData: Record<string, any> } = $props()
</script>

<!--
  The sender is taken from the signed-in account and is not editable, so this is
  a summary rather than a form card. It is a <section> with a heading so it can
  be found with getByRole('region', { name: 'Sender Information' }).
-->
<section aria-labelledby="sender-heading" class="bg-muted p-4 rounded-lg shadow border border-border">
  <div class="flex items-center gap-3">
    <div class="w-10 h-10 bg-nord-frost-1/20 rounded-full flex items-center justify-center">
      <User class="w-5 h-5 text-primary" aria-hidden="true" />
    </div>
    <div class="flex-1">
      <h2 id="sender-heading" class="text-sm font-medium text-muted-foreground">
        {t('form.senderInformation')}
      </h2>
      <p class="text-foreground font-semibold">
        {formData.senderName || ''} - {formData.senderCountry || ''}
      </p>
    </div>
  </div>
  <p class="text-xs text-muted-foreground/70 mt-3">
    Sender details are filled from your account automatically and cannot be edited
  </p>
</section>
