// app/register/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { t } from '@/lib/translations'
import { useAuth } from '@/contexts/AuthContext'

export default function RegisterPage() {
  const router = useRouter()
  const { refreshUser } = useAuth()
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const [formData, setFormData] = useState({
    // Account
    email: '',
    password: '',
    confirmPassword: '',
    // Personal Info
    fullName: '',
    phone: '',
    country: '',
    city: '',
    street: '',
    postalCode: '',
  })

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target
    setFormData((prev) => ({ ...prev, [name]: value }))
    setError(null)
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError(null)

    // Validate passwords match
    if (formData.password !== formData.confirmPassword) {
      setError('Passwords do not match')
      return
    }

    // Validate all fields
    if (
      !formData.email ||
      !formData.password ||
      !formData.fullName ||
      !formData.phone ||
      !formData.country ||
      !formData.city ||
      !formData.street ||
      !formData.postalCode
    ) {
      setError(t('errors.required'))
      return
    }

    setLoading(true)

    try {
      const response = await fetch('/api/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: formData.email,
          password: formData.password,
          fullName: formData.fullName,
          phone: formData.phone,
          country: formData.country,
          city: formData.city,
          street: formData.street,
          postalCode: formData.postalCode,
        }),
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || t('errors.registerFailed'))
      }

      // Success - refresh user context and redirect
      await refreshUser()
      router.push('/')
    } catch (err) {
      setError(err instanceof Error ? err.message : t('errors.registerFailed'))
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-background flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-2xl w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-foreground">
            {t('auth.registerTitle')}
          </h2>
        </div>

        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          {error && (
            <div className="bg-nord-aurora-red/20 border border-destructive text-destructive px-4 py-3 rounded">
              {error}
            </div>
          )}

          {/* Account Information */}
          <div className="bg-muted p-6 rounded-lg shadow border border-border">
            <h3 className="text-lg font-semibold mb-4 text-primary">Account Information</h3>
            <div className="space-y-4">
              <div>
                <label htmlFor="email" className="block text-sm font-medium text-muted-foreground">
                  {t('auth.email')} *
                </label>
                <input
                  id="email"
                  name="email"
                  type="email"
                  required
                  value={formData.email}
                  onChange={handleChange}
                  className="mt-3 w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
                  placeholder={t('placeholders.enterEmail')}
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label htmlFor="password" className="block text-sm font-medium text-muted-foreground">
                    {t('auth.password')} *
                  </label>
                  <input
                    id="password"
                    name="password"
                    type="password"
                    required
                    value={formData.password}
                    onChange={handleChange}
                    className="mt-3 w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
                    placeholder={t('placeholders.enterPassword')}
                  />
                </div>

                <div>
                  <label
                    htmlFor="confirmPassword"
                    className="block text-sm font-medium text-muted-foreground"
                  >
                    Confirm Password *
                  </label>
                  <input
                    id="confirmPassword"
                    name="confirmPassword"
                    type="password"
                    required
                    value={formData.confirmPassword}
                    onChange={handleChange}
                    className="mt-3 w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
                    placeholder="Re-enter your password"
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Personal Information */}
          <div className="bg-muted p-6 rounded-lg shadow border border-border">
            <h3 className="text-lg font-semibold mb-4 text-primary">Personal Information</h3>
            <p className="text-sm text-muted-foreground mb-4">
              This information will be used as your default sender details
            </p>
            <div className="space-y-4">
              <div>
                <label htmlFor="fullName" className="block text-sm font-medium text-muted-foreground">
                  {t('auth.fullName')} *
                </label>
                <input
                  id="fullName"
                  name="fullName"
                  type="text"
                  required
                  value={formData.fullName}
                  onChange={handleChange}
                  className="mt-3 w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
                  placeholder={t('placeholders.enterName')}
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label htmlFor="phone" className="block text-sm font-medium text-muted-foreground">
                    {t('auth.phone')} *
                  </label>
                  <input
                    id="phone"
                    name="phone"
                    type="tel"
                    required
                    value={formData.phone}
                    onChange={handleChange}
                    className="mt-3 w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
                    placeholder={t('placeholders.enterPhone')}
                  />
                </div>

                <div>
                  <label htmlFor="country" className="block text-sm font-medium text-muted-foreground">
                    {t('auth.country')} *
                  </label>
                  <select
                    id="country"
                    name="country"
                    required
                    value={formData.country}
                    onChange={handleChange}
                    className="mt-3 w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
                  >
                    <option value="">{t('placeholders.selectCountry')}</option>
                    <option value="Saudi Arabia">Saudi Arabia</option>
                    <option value="United Arab Emirates">United Arab Emirates</option>
                    <option value="Kuwait">Kuwait</option>
                    <option value="Bahrain">Bahrain</option>
                    <option value="Qatar">Qatar</option>
                    <option value="Oman">Oman</option>
                    <option value="Egypt">Egypt</option>
                    <option value="Jordan">Jordan</option>
                    <option value="Lebanon">Lebanon</option>
                    <option value="Iraq">Iraq</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label htmlFor="city" className="block text-sm font-medium text-muted-foreground">
                    {t('auth.city')} *
                  </label>
                  <input
                    id="city"
                    name="city"
                    type="text"
                    required
                    value={formData.city}
                    onChange={handleChange}
                    className="mt-3 w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
                    placeholder={t('placeholders.enterCity')}
                  />
                </div>

                <div>
                  <label htmlFor="postalCode" className="block text-sm font-medium text-muted-foreground">
                    {t('auth.postalCode')} *
                  </label>
                  <input
                    id="postalCode"
                    name="postalCode"
                    type="text"
                    required
                    value={formData.postalCode}
                    onChange={handleChange}
                    className="mt-3 w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
                    placeholder={t('placeholders.enterPostalCode')}
                  />
                </div>
              </div>

              <div>
                <label htmlFor="street" className="block text-sm font-medium text-muted-foreground">
                  {t('auth.street')} *
                </label>
                <input
                  id="street"
                  name="street"
                  type="text"
                  required
                  value={formData.street}
                  onChange={handleChange}
                  className="mt-3 w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
                  placeholder={t('placeholders.enterStreet')}
                />
              </div>
            </div>
          </div>

          <div>
            <button
              type="submit"
              disabled={loading}
              data-testid="register-button"
              className="register-button w-full flex justify-center py-3 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-nord-polar-0 bg-primary hover:bg-nord-frost-3 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary disabled:bg-nord-polar-3 disabled:cursor-not-allowed"
            >
              {loading ? t('common.loading') : t('auth.register')}
            </button>
          </div>
        </form>

        <p className="text-center text-sm text-muted-foreground">
          {t('auth.alreadyHaveAccount')}{' '}
          <Link href="/login" className="font-medium text-primary hover:text-nord-frost-3">
            {t('auth.loginHere')}
          </Link>
        </p>
      </div>
    </div>
  )
}

// src/routes/register/+page.svelte
<script lang="ts">
  import { goto, invalidateAll } from '$app/navigation'
  import countriesData from '$lib/rules/countries.json'
  import { t } from '$lib/translations'

  let form = $state({
    email: '',
    password: '',
    confirmPassword: '',
    fullName: '',
    phone: '',
    country: '',
    city: '',
    street: '',
    postalCode: '',
  })

  let loading = $state(false)
  let errorMessage = $state<string | null>(null)

  async function submit(e: SubmitEvent) {
    e.preventDefault()
    errorMessage = null

    if (form.password !== form.confirmPassword) {
      errorMessage = 'Passwords do not match'
      return
    }

    loading = true
    try {
      const { confirmPassword, ...payload } = form
      const response = await fetch('/api/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      })

      const data = await response.json()

      if (!response.ok) {
        errorMessage = data.error || t('errors.registerFailed')
        return
      }

      await invalidateAll()
      await goto('/')
    } catch (err) {
      errorMessage = err instanceof Error ? err.message : t('errors.registerFailed')
    } finally {
      loading = false
    }
  }
</script>

<svelte:head>
  <title>Sign Up - My Shipments</title>
</svelte:head>

<div class="min-h-screen bg-background flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-2xl w-full space-y-8">
    <div>
      <img src="/ship-logo.svg" alt="ShipApp" class="mx-auto h-14 w-14" />
      <h1 class="mt-6 text-center text-3xl font-extrabold text-foreground">
        {t('auth.registerTitle')}
      </h1>
    </div>

    <form class="mt-8 space-y-6" onsubmit={submit}>
      {#if errorMessage}
        <div
          role="alert"
          class="bg-nord-aurora-red/20 border border-destructive text-destructive px-4 py-3 rounded"
        >
          {errorMessage}
        </div>
      {/if}

      <fieldset class="bg-muted p-6 rounded-lg shadow border border-border">
        <legend class="text-lg font-semibold mb-4 text-primary">Account Information</legend>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div class="md:col-span-2">
            <label for="email" class="block text-sm font-medium text-muted-foreground mb-2">
              {t('auth.email')}
            </label>
            <input
              id="email"
              type="email"
              autocomplete="email"
              required
              bind:value={form.email}
              class="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
            />
          </div>
          <div>
            <label for="password" class="block text-sm font-medium text-muted-foreground mb-2">
              {t('auth.password')}
            </label>
            <input
              id="password"
              type="password"
              autocomplete="new-password"
              required
              bind:value={form.password}
              class="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
            />
          </div>
          <div>
            <label
              for="confirmPassword"
              class="block text-sm font-medium text-muted-foreground mb-2"
            >
              Confirm Password
            </label>
            <input
              id="confirmPassword"
              type="password"
              autocomplete="new-password"
              required
              bind:value={form.confirmPassword}
              placeholder="Re-enter your password"
              class="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
            />
          </div>
        </div>
      </fieldset>

      <fieldset class="bg-muted p-6 rounded-lg shadow border border-border">
        <legend class="text-lg font-semibold mb-4 text-primary">Personal Information</legend>
        <p class="text-sm text-muted-foreground mb-4">
          This information will be used as your default sender details
        </p>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label for="fullName" class="block text-sm font-medium text-muted-foreground mb-2">
              {t('auth.fullName')}
            </label>
            <input
              id="fullName"
              type="text"
              autocomplete="name"
              required
              bind:value={form.fullName}
              class="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
            />
          </div>
          <div>
            <label for="phone" class="block text-sm font-medium text-muted-foreground mb-2">
              {t('auth.phone')}
            </label>
            <input
              id="phone"
              type="tel"
              autocomplete="tel"
              required
              bind:value={form.phone}
              class="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
            />
          </div>
          <div class="md:col-span-2">
            <label for="country" class="block text-sm font-medium text-muted-foreground mb-2">
              {t('auth.country')}
            </label>
            <select
              id="country"
              required
              bind:value={form.country}
              class="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
            >
              <option value="">{t('placeholders.selectCountry')}</option>
              {#each countriesData.countries as country (country.code)}
                <option value={country.name}>{country.name}</option>
              {/each}
            </select>
          </div>
          <div>
            <label for="city" class="block text-sm font-medium text-muted-foreground mb-2">
              {t('auth.city')}
            </label>
            <input
              id="city"
              type="text"
              required
              bind:value={form.city}
              class="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
            />
          </div>
          <div>
            <label for="postalCode" class="block text-sm font-medium text-muted-foreground mb-2">
              {t('auth.postalCode')}
            </label>
            <input
              id="postalCode"
              type="text"
              autocomplete="postal-code"
              required
              bind:value={form.postalCode}
              class="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
            />
          </div>
          <div class="md:col-span-2">
            <label for="street" class="block text-sm font-medium text-muted-foreground mb-2">
              {t('auth.street')}
            </label>
            <input
              id="street"
              type="text"
              autocomplete="street-address"
              required
              bind:value={form.street}
              class="w-full px-3 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary bg-nord-polar-2 text-foreground"
            />
          </div>
        </div>
      </fieldset>

      <button
        type="submit"
        disabled={loading}
        class="w-full flex justify-center py-3 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-nord-polar-0 bg-primary hover:bg-nord-frost-3 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary disabled:bg-nord-polar-3 disabled:cursor-not-allowed"
      >
        {loading ? t('common.loading') : t('auth.register')}
      </button>
    </form>

    <p class="text-center text-sm text-muted-foreground">
      {t('auth.alreadyHaveAccount')}
      <a href="/login" class="font-medium text-primary hover:text-nord-frost-3">
        {t('auth.loginHere')}
      </a>
    </p>
  </div>
</div>
