// src/lib/components/agent/Markdown.svelte
<script lang="ts">
  import { marked } from 'marked'
  import DOMPurify from 'dompurify'

  /**
   * Renders model output as Markdown.
   *
   * The models reply in Markdown (bold labels, bullet lists, the occasional
   * table), so rendering it as plain text shows literal asterisks.
   *
   * The output is sanitised before it reaches {@html}: this is model text that
   * can echo back retrieved document content, so it is never trusted markup.
   */
  let { content, compact = false }: { content: string; compact?: boolean } = $props()

  const html = $derived.by(() => {
    const raw = marked.parse(content ?? '', { async: false }) as string
    // DOMPurify needs a DOM; during SSR we render nothing and let the client
    // hydrate, which is fine because chat output only ever arrives client-side.
    return typeof window === 'undefined' ? '' : DOMPurify.sanitize(raw)
  })
</script>

<div class="markdown min-w-0 space-y-2" class:compact>
  <!-- eslint-disable-next-line svelte/no-at-html-tags -- sanitised above -->
  {@html html}
</div>

<style>
  .markdown :global(p) {
    line-height: 1.625;
  }
  .markdown :global(strong) {
    font-weight: 600;
    color: theme('colors.foreground');
  }
  .markdown :global(em) {
    font-style: italic;
  }
  .markdown :global(ul) {
    list-style: disc;
    padding-left: 1.25rem;
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }
  .markdown :global(ol) {
    list-style: decimal;
    padding-left: 1.25rem;
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }
  .markdown :global(h1),
  .markdown :global(h2) {
    font-size: 1rem;
    font-weight: 700;
    margin-top: 0.75rem;
  }
  .markdown :global(h3) {
    font-size: 0.875rem;
    font-weight: 700;
    margin-top: 0.75rem;
  }
  .markdown :global(code) {
    padding: 0.125rem 0.25rem;
    border-radius: 0.25rem;
    background: theme('colors.nord.polar.3');
    font-family: theme('fontFamily.mono');
    font-size: 0.9em;
  }
  .markdown :global(pre) {
    padding: 0.75rem;
    border-radius: 0.25rem;
    background: theme('colors.nord.polar.3');
    overflow-x: auto;
    font-size: 0.75rem;
  }
  .markdown :global(blockquote) {
    border-left: 2px solid theme('colors.border');
    padding-left: 0.75rem;
    color: theme('colors.muted-foreground');
  }
  .markdown :global(a) {
    color: theme('colors.primary');
    text-decoration: underline;
  }

  /*
    A wide table must scroll inside its own box, never stretch the chat panel.
    max-width binds the scroller to the bubble's resolved width; the table is
    sized to content so there is something to scroll.
  */
  .markdown :global(table) {
    display: block;
    max-width: 100%;
    overflow-x: auto;
    border-collapse: collapse;
    text-align: left;
  }
  .markdown :global(th),
  .markdown :global(td) {
    border: 1px solid theme('colors.border');
    padding: 0.25rem 0.5rem;
  }
  .markdown :global(th) {
    font-weight: 600;
    white-space: nowrap;
  }
  .compact :global(table) {
    font-size: 0.75rem;
  }
  .compact :global(th),
  .compact :global(td) {
    padding: 0.25rem 0.375rem;
  }
</style>

// components/agent/Markdown.tsx
'use client'

import ReactMarkdown from 'react-markdown'

/**
 * Renders model output as Markdown.
 *
 * The models reply in Markdown (bold labels, bullet lists, occasional tables), so
 * rendering it as plain text shows literal asterisks. react-markdown does not
 * render raw HTML unless you add rehype-raw, so model output cannot inject markup.
 *
 * Elements are styled explicitly rather than via @tailwindcss/typography, which
 * this project does not use.
 *
 * The wrapper keeps whatever data-testid the caller passes, and Markdown rendering
 * preserves text content, so assertions like
 * `getByTestId('assistant-answer')).toContainText('$82.00')` keep working.
 */
export default function Markdown({
  children,
  testId,
  className = '',
  compact = false,
}: {
  children: string
  testId?: string
  className?: string
  /** Tighter styling for the narrow chat panel. */
  compact?: boolean
}) {
  return (
    <div data-testid={testId} className={`space-y-2 min-w-0 ${className}`}>
      <ReactMarkdown
        components={{
          p: ({ children }) => <p className="leading-relaxed">{children}</p>,
          strong: ({ children }) => (
            <strong className="font-semibold text-foreground">{children}</strong>
          ),
          em: ({ children }) => <em className="italic">{children}</em>,
          ul: ({ children }) => <ul className="list-disc pl-5 space-y-1">{children}</ul>,
          ol: ({ children }) => <ol className="list-decimal pl-5 space-y-1">{children}</ol>,
          li: ({ children }) => <li className="leading-relaxed">{children}</li>,
          h1: ({ children }) => <h1 className="text-base font-bold mt-3">{children}</h1>,
          h2: ({ children }) => <h2 className="text-base font-bold mt-3">{children}</h2>,
          h3: ({ children }) => <h3 className="text-sm font-bold mt-3">{children}</h3>,
          code: ({ children }) => (
            <code className="px-1 py-0.5 rounded bg-nord-polar-3 font-mono text-[0.9em]">
              {children}
            </code>
          ),
          pre: ({ children }) => (
            <pre className="p-3 rounded bg-nord-polar-3 overflow-x-auto font-mono text-xs">
              {children}
            </pre>
          ),
          blockquote: ({ children }) => (
            <blockquote className="border-l-2 border-border pl-3 text-muted-foreground">
              {children}
            </blockquote>
          ),
          a: ({ href, children }) => (
            <a
              href={href}
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary underline"
            >
              {children}
            </a>
          ),
          hr: () => <hr className="border-border" />,
          // A wide table must scroll inside its own box, never stretch the panel.
          // max-w-full binds the scroll container to the bubble's resolved width;
          // w-max lets the table exceed it so there is something to scroll.
          table: ({ children }) => (
            <div className="overflow-x-auto max-w-full -mx-1 px-1">
              <table
                className={`w-max min-w-full border-collapse text-left ${
                  compact ? 'text-xs' : ''
                }`}
              >
                {children}
              </table>
            </div>
          ),
          th: ({ children }) => (
            <th
              className={`border border-border font-semibold whitespace-nowrap ${
                compact ? 'px-1.5 py-1' : 'px-2 py-1'
              }`}
            >
              {children}
            </th>
          ),
          td: ({ children }) => (
            <td
              className={`border border-border align-top ${
                compact ? 'px-1.5 py-1' : 'px-2 py-1'
              }`}
            >
              {children}
            </td>
          ),
        }}
      >
        {children}
      </ReactMarkdown>
    </div>
  )
}
